name: ci-keycloak-client-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.12.3-otp-24"
      - run: mix deps.get
      - run: mix test
